### ISSUE TITLE
Implement Batch Importer with Schema Selection and CSV Upload

### ISSUE THREAD

**Issue by vthwang** [MurmurationsNetwork/MurmurationsToolsSvelte#108]
- [x] Select a schema for importing
- [x] Input a batch title
- [x] Choose a CSV file to upload
- [x] Validate the uploaded CSV file before saving the records.
- [x] Store the imported records into MongoDB after validation.
- [x] Provide user feedback on validation errors or successful uploads.

**Comment by geoffturk** [comment]
Closed by #140
